services:
  torchserve:
    image: fusa-torchserve
    container_name: fusa-torchserve
    command:
      - 'torchserve --start --ncs --ts-config config.properties'
    ports:
      - "7070:7070"
      - "7071:7071"
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
    networks:
      - monitoring
    volumes:
      - ./model-store:/home/model-server/model-store

  node:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    pid: host
    networks:
      - monitoring
    expose:
      - 9100
    command:
      - '--path.rootfs=/rootfs'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    expose:
      - 9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    networks:
      - monitoring
    depends_on:
      - node
      - torchserve

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    user: "$UID"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pasameavault
    depends_on:
      - prometheus


networks:
  monitoring:
    driver: bridge

