global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'torchserve'
    static_configs:
    - targets: ['172.17.0.2:8082'] #TorchServe metrics endpoint
  - job_name: 'node'
    static_configs:
    - targets: ['172.17.0.1:9100']
